---
- name: "Check war files in release"
  local_action: stat path="/DevOps_Do_Not_Delete/SDK/{{item}}"
  #state: file
  register: result
  #checksum: yes
  #archive: no
  with_items:
    - "{{SDK_FILES}}"