---
- name: "Check war files in release"
  local_action: stat path="{{DEVOPS_BASE_DIR}}/SDK/{{item}}"
  #state: file
  register: result
  #checksum: yes
  #archive: no
  with_items:
    - "{{SDK_FILES}}"
    
- name: "Download SDK"
  get_url:
    url: "{{SDK_URL}}{{item}}"
    dest: "{{DEVOPS_BASE_DIR}}/SDK"
  with_items:
    - "{{SDK_FILES}}"
  when: result.stat.exists == True  
    