---
all_components: ["SDK","WAS9","FP09","IM"]
base_components: ["WAS9","FP09","IM"]

install_parent_dir: "/opt/tools"
create_dir_during_install: ["IBM/WebSphere/AppServer/", "IBM/InstallationManager/"]
temp: "/tmp"
DEVOPS_BASE_DIR: "/DevOps_Do_Not_Delete"
########################################################################
ARTIFACTORY_URL: "https://maven.etb.tieto.com/artifactory/fs-pcm-misc"
SDK_URL: "{{ARTIFACTORY_URL}}/IBM/AppServer/WebSphere/WAS9.0/SDK/"
WAS9_URL: "{{ARTIFACTORY_URL}}/IBM/AppServer/WebSphere/WAS9.0/WAS/"
FP09_URL: "{{ARTIFACTORY_URL}}/IBM/AppServer/WebSphere/WAS9.0/FP9/"
IM_URL: "{{ARTIFACTORY_URL}}/IBM/AppServer/WebSphere/WAS9.0/IM/"
SDK_FILES: ["was.repo.9000.java8_part1.zip","was.repo.9000.java8_part2.zip","was.repo.9000.java8_part3.zip"]
WAS9_FILES: "was.repo.9000.base.zip"
FP09_FILES: "9.0.0-WS-WAS-FP009.zip"
IM_FILES: "agent.installer.lnx.gtk.x86_64_1.8.5.zip"
########################################################################
imcl: "{{DEVOPS_BASE_DIR}}/IM/tools/imcl"
INSTALL_IIM_LOG_FILE: "/tmp/INSTALL_IIM.log"
INSTALL_IIM_DIR: "{{install_parent_dir}}/IBM/InstallationManager/"
