---
components: ["SDK","WAS9","WASFP09"]
components_dir: ["DOWNLOAD_MASTER_DIR","WAS9.0_DIR","SDK_DIR","WASFP09_DIR"]
DOWNLOAD_MASTER_DIR: /DevOps_Do_Not_Delete
WAS9.0_DIR: {{ DOWNLOAD_MASTER_DIR }}/WAS9.0/
SDK_DIR: {{ DOWNLOAD_MASTER_DIR }}/SDK/
WASFP09_DIR: {{ DOWNLOAD_MASTER_DIR }}/WASFP09/
